### ISSUE TITLE
box isn't viewable while dragging/resizing

### ISSUE THREAD

**Issue by dannypadilla** [dannypadilla/image-cropper-gui#3]

**Comment by aldomadrid** [comment]
To draw a square as you drag the mouse over the image: 
 1. Add code for when the mouse is moving: 
      if event == cv2.EVENT_MOUSEMOVE:
           //code
 2. Add code so that a square is drawn on the image as the mouse moves
     if event == cv2.EVENT_MOUSEMOVE:
           if moving:
                tempImg = img.clone()
                cv2.rectangle(img, Point(x1, y1), Point(x2, y2), 3)
                cv2.imshow("img", tempImg);

**Comment by dannypadilla** [comment]
That helped a lot. Thanks!
